-   id: pyproject-flake8
    name: pyproject-flake8
    description: '`pyproject-flake8` is a variant of `flake8` with support for configuration in the `pyproject.toml` file.'
    entry: flake8
    language: python
    types: [python]
    require_serial: true
