name: Build package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel build
      - name: Building packages
        run: python -m build
      - uses: actions/upload-artifact@v2
        # if: startsWith(github.ref, 'refs/tags')
        with:
          name: package
          path: dist/*
#       - name: Publish distribution 📦 to Test PyPI
#         uses: pypa/gh-action-pypi-publish@master
#         with:
#           password: ${{ secrets.TEST_PYPI_API_TOKEN }}
#           repository_url: https://test.pypi.org/legacy/
#       - name: Publish distribution 📦 to PyPI
#         if: startsWith(github.ref, 'refs/tags')
#         uses: pypa/gh-action-pypi-publish@master
#         with:
#           password: ${{ secrets.PYPI_API_TOKEN }}